// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5RBLSc2EboZTvuYkwX10GjFIwWS_BNyY',
    appId: '1:270856090279:web:3ea98224611a991a88e182',
    messagingSenderId: '270856090279',
    projectId: 'platzitripssplatzi',
    authDomain: 'platzitripssplatzi.firebaseapp.com',
    storageBucket: 'platzitripssplatzi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRhtRDL8bK2Iq0-UE0kdfMfcv2570Hx2E',
    appId: '1:270856090279:android:ff6932d5db1e389188e182',
    messagingSenderId: '270856090279',
    projectId: 'platzitripssplatzi',
    storageBucket: 'platzitripssplatzi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd9JwykcVlt55R_HCb5a9yoo87DtpGdDU',
    appId: '1:270856090279:ios:d534f76b9fa6bcf188e182',
    messagingSenderId: '270856090279',
    projectId: 'platzitripssplatzi',
    storageBucket: 'platzitripssplatzi.appspot.com',
    iosClientId:
        '270856090279-rv5ubhu4ii1o6q2lnaaem0ec38ll46sg.apps.googleusercontent.com',
    iosBundleId: 'com.example.platziTripssApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd9JwykcVlt55R_HCb5a9yoo87DtpGdDU',
    appId: '1:270856090279:ios:d534f76b9fa6bcf188e182',
    messagingSenderId: '270856090279',
    projectId: 'platzitripssplatzi',
    storageBucket: 'platzitripssplatzi.appspot.com',
    iosClientId:
        '270856090279-rv5ubhu4ii1o6q2lnaaem0ec38ll46sg.apps.googleusercontent.com',
    iosBundleId: 'com.example.platziTripssApp',
  );
}
